runtime: nodejs20
service: notes-frontend-veriaw  # ganti nama service kalau mau
instance_class: F1

handlers:
  - url: /
    static_files: dist/index.html
    upload: build/index.html

  - url: /(.*)
    static_files: dist/\1
    upload: build/(.*)

default_expiration: "1h"